language: node_js
node_js:
  - 11.9.0

install: 
  - npm install

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: AWS_ACCESS_KEY_ID
  secret_access_key:
    secure: AWS_SECRET_ACCESS_KEY
  region: "eu-west-2"
  app: "slackify"
  env: "slackify-env"
